function f2v1Head = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  F2V1HEAD = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  F2V1HEAD = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  f2v1Head = importfile("/Users/eduardosaman/Desktop/MATLAB/RESULTS/f2/f2v1/f2v1_Head.csv", [1, 2]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-May-2022 17:28:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, 2];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7"], "ThousandsSeparator", ",");

% Import the data
f2v1Head = readtable(filename, opts);

%% Convert to output type
f2v1Head = table2array(f2v1Head);
end