"""
Build supplementary.tex (Online Resource 1) from the table produced by
pca_loadings.py.

The table is turned into a longtable so that it starts directly under the
introductory paragraph instead of floating to a page of its own, and so that
it would carry its header over to a second page if it ever grew.
"""
import re

TAB = 'tab_pca.tex'
OUT = 'supplementary.tex'

HEAD_ROWS = (
    "\\toprule\n"
    "& \\multicolumn{5}{c}{Principal components}\\\\\n"
    "\\cmidrule(l){2-6}\n"
    "Features & PC1 & PC2 & PC3 & PC4 & PC5\\\\\n"
    "(variance explained) & (42.5\\%) & (20.3\\%) & (14.0\\%) & (8.5\\%) "
    "& (5.7\\%)\\\\\n"
    "\\midrule\n")

PREAMBLE = r"""%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Online Resource 1 - separate file, uploaded alongside the manuscript.
%% Springer Nature asks that each supplementary file repeat the article
%% title, the journal name, the authors and the corresponding address.
%% Generated by build_supplementary.py; compile with pdflatex -> ESM_1.pdf.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[10pt]{article}
\usepackage[a4paper,top=1.8cm,bottom=1.8cm,left=2.0cm,right=2.0cm]{geometry}
\usepackage{graphicx,amsmath,amssymb,array,booktabs,xcolor,textcomp}
\usepackage{longtable}
\setlength{\abovecaptionskip}{8pt}
\setlength{\belowcaptionskip}{7pt}
\renewcommand{\thetable}{S\arabic{table}}
\pagestyle{plain}

\begin{document}

\begin{center}
{\large\bfseries Online Resource 1\par}
\vspace{2pt}
{\small Supplementary material for the article\par}
\vspace{5pt}
{\bfseries Revealing latent motion features in scoliotic zebrafish:\\
from nonlinear dynamics to machine-learning classification\par}
\vspace{4pt}
X.\ Marimon, E.\ Saman-Sakkal, M.\ Cerrolaza, J.\ Bosch-Bayard, A.\ Portela\\[3pt]
\emph{Nonlinear Dynamics}, Topical Collection ``Biosystem Dynamics''\\[3pt]
{\small Corresponding authors: X.\ Marimon, Department of Strength of Materials
and Structural Engineering, Universitat Polit\`{e}cnica de Catalunya
(UPC-BarcelonaTECH), Barcelona, Spain, xavier.marimon@upc.edu;
E.\ Saman-Sakkal, University College Dublin, Belfield, Dublin, Ireland,
eduardo.saman@ucdconnect.ie}
\end{center}
\vspace{2pt}

\noindent
The unsupervised analysis of the main text summarises the thirty-three-feature
matrix by its leading principal components. Their full composition is reported
here rather than in the article, because it describes this particular sample
rather than a result: only one coefficient in the whole matrix is determined to
better than a tenth of its own size, and beyond the second component the
ordering of the components is not preserved under resampling. Each feature is
given as name, symbol and unit; (--) marks a dimensionless quantity.

"""


def main():
    tab = open(TAB).read()
    caption = re.search(r'(\\caption\{.*?\})\n\\label', tab, re.S).group(1)
    body = re.search(r'\\midrule\n(.*?)\\bottomrule', tab, re.S).group(1).rstrip()

    lt = ("%---------------------------------------------------------------- TAB S1\n"
          "\\begingroup\n\\scriptsize\n\\setlength{\\tabcolsep}{0pt}\n"
          "\\renewcommand{\\arraystretch}{0.82}\n"
          "\\setlength{\\LTleft}{0pt}\\setlength{\\LTright}{0pt}\n"
          "\\setlength{\\LTcapwidth}{\\textwidth}\n"
          "\\begin{longtable}"
          "{@{\\extracolsep{\\fill}}>{\\raggedright\\arraybackslash}"
          "p{0.40\\textwidth}rrrrr@{}}\n"
          + caption + "\\label{tab:S1}\\\\\n"
          + HEAD_ROWS + "\\endfirsthead\n"
          "\\multicolumn{6}{@{}l}{\\itshape Table S1, continued}\\\\[2pt]\n"
          + HEAD_ROWS + "\\endhead\n"
          "\\midrule\n"
          "\\multicolumn{6}{r@{}}{\\itshape continued on the next page}\\\\\n"
          "\\endfoot\n\\bottomrule\n\\endlastfoot\n"
          + body + "\n\\end{longtable}\n\\endgroup\n")

    open(OUT, 'w').write(PREAMBLE + lt + "\n\\end{document}\n")
    print('ok', OUT, '| rows:', body.count('\\quad'))


if __name__ == '__main__':
    main()
